MvcBlogg/Models/ORM/Entity/BlogPost.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcBlogg.Models.ORM.Entity
{
    public class BlogPost : BaseEntity
    {
        public string Title { get; set; }
        public string Content { get; set; }


        public int CategoryId { get; set; }

        public string ImagePath { get; set; }

        [ForeignKey("CategoryId")]
        public virtual Category Category { get; set; }

        public virtual List<BlogPostComment> BlogPostComment { get; set; }

    }
}

MvcBlogg/Areas/Admin/Controllers/BlogPostController.cs
using MvcBlogg.Areas.Admin.Models.DTO;
using MvcBlogg.Areas.Admin.Models.Services;
using MvcBlogg.Models.ORM.Entity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace MvcBlogg.Areas.Admin.Controllers
{
    public class BlogPostController : BaseController
    {
        // GET: Admin/BlogPost
        public ActionResult Index()
        {
            List<BlogPostVm> model = db.BlogPosts.Where(x => x.IsDeleted == false)
                .OrderBy(x => x.AddDate)
                .Select(x => new BlogPostVm()
                {
                    ID = x.ID,
                    Title = x.Title,
                    CategoryName = x.Category.Name
                }).ToList();

            return View(model);
        }

        public ActionResult AddBlogPost()
        {
            BlogPostVm model = new BlogPostVm();
            model.drpCategories = DrpServices.getDrpCategories();

            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult AddBlogPost(BlogPostVm model)
        {
            BlogPostVm vmodel = new BlogPostVm();
            vmodel.drpCategories = DrpServices.getDrpCategories();



            if (ModelState.IsValid)
            {

                string fileName = "";
                foreach (string name in Request.Files)
                {
                    model.PostImage = Request.Files[name];
                    //string imgNumber = Guid.NewGuid().ToString();
                    string ext = Path.GetExtension(model.PostImage.FileName);
                    if (ext==".jgp"||ext==".jpeg"||ext=="png")
                    {
                        fileName = model.PostImage.FileName;
                        model.PostImage.SaveAs(Server.MapPath("~/Uploads/Images/" + fileName));
                    }                    
                }
                BlogPost blogpost = new BlogPost();
                blogpost.CategoryId = model.CategoryId;
                blogpost.Title = model.Title;
                blogpost.Title = model.Title;
                blogpost.Content = model.Content;
                blogpost.ImagePath = fileName;

                db.BlogPosts.Add(blogpost);
                ViewBag.IsSuccess = 1;
                db.SaveChanges();
                return View(vmodel);
            }
            else
            {
                ViewBag.IsSuccess = 2;
                return View(vmodel);
            }
        }

        public ActionResult UpdateBlog(int id)
        {

            BlogPost blogpost = db.BlogPosts.FirstOrDefault(x => x.ID == id);
            BlogPostVm model = new BlogPostVm();
            model.Title = blogpost.Title;
            model.CategoryId = blogpost.CategoryId;
            model.Content = blogpost.Content;
            model.drpCategories = DrpServices.getDrpCategories();

            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult UpdateBlog(BlogPostVm model)
        {
            model.drpCategories = DrpServices.getDrpCategories();

            if (ModelState.IsValid)
            {
                BlogPost blogpost = db.BlogPosts.FirstOrDefault(x => x.ID == model.ID);
                blogpost.CategoryId = model.CategoryId;
                blogpost.Title = model.Title;
                blogpost.Content = model.Content;

                db.SaveChanges();
                ViewBag.IsSuccess = 1;
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.IsSuccess = 2;
                return View(model);
            }
        }

        public JsonResult DeleteBlog(int id)
        {
            BlogPost blogpost = db.BlogPosts.FirstOrDefault(x => x.ID == id);
            blogpost.IsDeleted = true;
            blogpost.DeleteDate = DateTime.Now;
            db.SaveChanges();

            return Json("");
        }
    }
}

MvcBlogg/Areas/Admin/Views/BlogPost/AddBlogPost.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
    ViewBag.Title = "AddBlogPost";
}

<section class="content-header">
    <h1>
        BLog Post
        <small>Add new</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Forms</a></li>
        <li class="active">General Elements</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-10">
            @Html.Partial("_FormMessagesPartial")
            @using (Html.BeginForm("AddBlogPost", "BlogPost", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.Partial("_BlogPost")
            }
        </div>
    </div>
</section>

MvcBlogg/Areas/Admin/Views/BlogPost/Index.cshtml
@model List<MvcBlogg.Areas.Admin.Models.DTO.BlogPostVm>

@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
    ViewBag.Title = "Index";
}

<link href="~/Areas/Admin/Content/css/dataTables.bootstrap.css" rel="stylesheet" />
<script src="~/Areas/Admin/Content/Scripts/jquery.dataTables.min.js"></script>
<script src="~/Areas/Admin/Content/Scripts/dataTables.bootstrap.min.js"></script>
<script src="~/Areas/Admin/Content/Scripts/custom/deleteRecord.js"></script>

<section class="content-header">
    <h1>
        Blog List
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Tables</a></li>
        <li class="active">Category List</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">

            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Data Table With Full Features</h3>
                </div>
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Title</th>
                                <th>Category</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr id="a_@item.ID">
                                    <td>@item.ID</td>
                                    <td>@item.Title</td>
                                    <td>@item.CategoryName</td>
                                    <td><a href="/Admin/BlogPost/UpdateBlog/@item.ID">Edit</a></td>
                                    <td>
                                        <img style="cursor:pointer" onclick="Delete('/Admin/BlogPost/DeleteBlog/',@item.ID)" height="15" width="15" src="~/Areas/Admin/Content/images/delete.png" />
                                    </td>
                                </tr>
                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>ID</th>
                                <th>Title</th>
                                <th>Category</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
        $(function () {
            $("#example1").DataTable();
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false
            });
        });
</script>

MvcBlogg/Areas/Admin/Views/BlogPost/UpdateBlog.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
    ViewBag.Title = "Update Blog";
}
<section class="content-header">
    <h1>
        Update Post
        <small>Add new</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Forms</a></li>
        <li class="active">General Elements</li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-10">
            @Html.Partial("_FormMessagesPartial")
            @using (Html.BeginForm("UpdateBlog", "BlogPost", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.Partial("_BlogPost")
            }
        </div>
    </div>
</section>